### ISSUE TITLE
Support for Nautical Miles in units

### ISSUE THREAD

**Issue by 4G-Gregg** [vincentneo/Avenue-GPX-Viewer#11]
I'm loving this app but my primary use case is tracking sailing races. Adding support for Nautical Miles would be fantastic, especially in quick look.

**Comment by 4G-Gregg** [comment]
I see you are using the system's setting for units. I guess we'd have to push this into preferences as well to choose your units. Would you have any opposition to that method? There's a chance I might have time to add this myself but would like to agree on the approach.

**Comment by vincentneo** [comment]
@4G-Gregg 
Apologies! I haven’t been actively monitoring this space, since it doesn’t usually get much attention. But really sorry for the long wait.

As for your question, I think having it in the preferences is a logical choice, and I agree with that.
