### ISSUE TITLE
Xcode-Compatible GPX Not Loaded

### ISSUE THREAD

**Issue by VaslD** [vincentneo/Avenue-GPX-Viewer#17]
I think this is a duplicate of https://github.com/vincentneo/Avenue-GPX-Viewer/issues/9, but since I don't know how to re-open an issue...

I have an Xcode-compatible GPX modified from template:

```xml
<?xml version="1.0"?>
<gpx version="1.1" creator="Xcode">
    
    <wpt lat="31.17122146982024" lon="121.0126880692052">
        <name>Minhang Dist., SH, China</name>
    </wpt>
    
</gpx>
```

This should puts me somewhere in Shanghai, China. But Avenue shows the middle of Atlantic Ocean instead. Took me a while to realize this looks like (0, 0) the other issue was talking about.

If I had to guess, it's because the Xcode example uses Waypoints (`<wpt>`) and you're reading Track Segments/Points (`<trkseg>`/`<trkpt>`).

I don't mind if there's an output that Avenue doesn't read. There's thousands of GPS handheld devices out there, and there's got to be some weird or legit format that's not supported. But you really SHOULD NOT fail silently or even show fallback results without explicit warning. Say something went wrong, please.

**Comment by vincentneo** [comment]
Sorry for the delay! 
Latest commit brings a change that takes waypoints into account when zooming in, when file loads.
