### ISSUE TITLE
.gpx file icon is either blank or is generic text file icon

### ISSUE THREAD

**Issue by vincentneo** [vincentneo/Avenue-GPX-Viewer#26]
Reported via email. 

OS: macOS High Sierra.

**Comment by pvdb** [comment]
> OS: `macOS High Sierra`

This is also(?)/still(?) an issue on `macOS Ventura 13.1` AFAICT

<img width="559" alt="210851883-df53788d-00c6-4457-b1b4-b8dd938d8092" src="https://user-images.githubusercontent.com/17322/210864341-79975399-4b30-40ea-8ce2-3f28d7d89e7d.png">

**Comment by vincentneo** [comment]
yup still an issue.
