### ISSUE TITLE
Feature request - some way to know which direction the route goes

### ISSUE THREAD

**Issue by tkafka** [vincentneo/Avenue-GPX-Viewer#28]
Hi, I live Avenue, but recently I used it to open gpx trails for a race, and I wasn't sure where is the start and the end.

I have a few ideas how to solve this:
- a green flag icon at the start, and finish line checkered flag at the end
- an option to show directional arrows on the line
- a mouse tooltip when hovering the line, showing distance from start - I could then mouse over the track to see where is the strat and the finish
- a slight gradient between start and the end (so eg. start could be darker?)

Would one of these work?

**Comment by vincentneo** [comment]
@tkafka sorry for the late reply, I only saw this today! 😓

I think implementation wise, option 1 could be the easiest. Ideally I think option 2 would be the clearest. I will definitely add this to my considerations when I have the time to update Avenue.

**Comment by vincentneo** [comment]
@tkafka, I think you might like this! Coming soon!
![gif](https://user-images.githubusercontent.com/23420208/212525873-8df97942-c440-4ce4-b599-549346c0bb83.gif)
